repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: docs/
      - id: trailing-whitespace
        exclude: docs/
      - id: check-merge-conflict
  - repo: https://github.com/golangci/golangci-lint
    rev: c0d3ddc9cf3faa61a4e378e879ece580256d76e5 # v2.12.2
    hooks:
      - id: golangci-lint
        args: [--fix]
        language: system
