package schemas

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

type OidcConfig struct {
	Audience     types.String `tfsdk:"audience"`
	SigningPKCS8 types.String `tfsdk:"pkcs8"`
	SigningKey   types.String `tfsdk:"signing_key"`
	Issuer       types.String `tfsdk:"issuer"`
	JWKSKeys     types.String `tfsdk:"jwks_keys"`
}

func (m OidcConfig) Schema() schema.Attribute {
	return schema.SingleNestedAttribute{
		Optional:    true,
		Description: "Configuration for integrating an OpenID Connect (OIDC) provider with the K3s cluster. This allows for authentication using OIDC tokens.",
		Attributes: map[string]schema.Attribute{
			"audience": schema.StringAttribute{
				Required:            true,
				Sensitive:           true,
				MarkdownDescription: "The audience that this ID token is intended for. This is a required field.",
			},
			"pkcs8": schema.StringAttribute{
				Required:            true,
				Sensitive:           true,
				MarkdownDescription: "The public signing key in PKCS8 format for verifying OIDC tokens.",
			},
			"signing_key": schema.StringAttribute{
				Required:            true,
				Sensitive:           true,
				MarkdownDescription: "The private signing key for signing OIDC tokens.",
			},
			"issuer": schema.StringAttribute{
				Required:            true,
				Sensitive:           true,
				MarkdownDescription: "The URL of the OIDC issuer. This is a required field.",
			},
			"jwks_keys": schema.StringAttribute{
				Computed:            true,
				Sensitive:           true,
				MarkdownDescription: "The JSON Web Key Set (JWKS) generated by the K3s cluster after configuring the OIDC provider. This is a computed attribute.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}
func (n OidcConfig) Validate() error {
	return nil
}

func (m *OidcConfig) ToObject(ctx context.Context) basetypes.ObjectValue {
	return ToObject(ctx, m)
}

func (m OidcConfig) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"audience":    types.StringType,
		"pkcs8":       types.StringType,
		"signing_key": types.StringType,
		"issuer":      types.StringType,
		"jwks_keys":   types.StringType,
	}
}

// func (m OidcConfig) configureServer(server k3s.ServerOidc) {
// 	server.AddOidc(
// 		m.Audience.ValueString(),
// 		m.Issuer.ValueString(),
// 		m.SigningPKCS8.ValueString(),
// 		m.SigningKey.ValueString(),
// 	)
// }

// func (m *OidcConfig) setJwks(client ssh_client.SSHClient) error {
// 	res, err := client.Run("sudo k3s kubectl get --raw /openid/v1/jwks")
// 	if err != nil {
// 		return fmt.Errorf("fetching status jwks key: %s", err.Error())
// 	}

// 	m.JWKSKeys = types.StringValue(res[0])
// 	return nil
// }
