package schemas

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

type OidcConfig struct {
	Audience     types.String `tfsdk:"audience"`
	SigningPKCS8 types.String `tfsdk:"pkcs8"`
	SigningKey   types.String `tfsdk:"signing_key"`
	Issuer       types.String `tfsdk:"issuer"`
	JWKSKeys     types.String `tfsdk:"jwks_keys"`
}

func (m OidcConfig) Schema() schema.Attribute {
	return schema.SingleNestedAttribute{
		Optional:    true,
		Description: "Configuration for integrating an OpenID Connect (OIDC) provider with the K3s cluster. This allows for authentication using OIDC tokens.",
		PlanModifiers: []planmodifier.Object{
			objectplanmodifier.UseStateForUnknown(),
		},
		Attributes: map[string]schema.Attribute{
			"audience": schema.StringAttribute{
				Optional:            true,
				Sensitive:           true,
				MarkdownDescription: "The audience that this ID token is intended for. Required when OIDC is configured.",
			},
			"pkcs8": schema.StringAttribute{
				Optional:            true,
				Sensitive:           true,
				MarkdownDescription: "The public signing key in PKCS8 format for verifying OIDC tokens. Required when OIDC is configured.",
			},
			"signing_key": schema.StringAttribute{
				Optional:            true,
				Sensitive:           true,
				MarkdownDescription: "The private signing key for signing OIDC tokens. Required when OIDC is configured.",
			},
			"issuer": schema.StringAttribute{
				Optional:            true,
				Sensitive:           true,
				MarkdownDescription: "The URL of the OIDC issuer. Required when OIDC is configured.",
			},
			"jwks_keys": schema.StringAttribute{
				Computed:            true,
				Sensitive:           true,
				MarkdownDescription: "The JSON Web Key Set (JWKS) generated by the K3s cluster after configuring the OIDC provider. This is a computed attribute.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}
func (n OidcConfig) Validate() error {
	missing := []string{}
	if n.Audience.IsNull() {
		missing = append(missing, "audience")
	}
	if n.SigningPKCS8.IsNull() {
		missing = append(missing, "pkcs8")
	}
	if n.SigningKey.IsNull() {
		missing = append(missing, "signing_key")
	}
	if n.Issuer.IsNull() {
		missing = append(missing, "issuer")
	}
	if len(missing) > 0 {
		return fmt.Errorf("oidc requires %s when configured", strings.Join(missing, ", "))
	}
	return nil
}

func (m *OidcConfig) ToObject(ctx context.Context) basetypes.ObjectValue {
	return ToObject(ctx, m)
}

func (m OidcConfig) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"audience":    types.StringType,
		"pkcs8":       types.StringType,
		"signing_key": types.StringType,
		"issuer":      types.StringType,
		"jwks_keys":   types.StringType,
	}
}
